from fastapi import FastAPI, HTTPException
from fastapi.responses import FileResponse
from fastapi.middleware.cors import CORSMiddleware
import os

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Generates a simple text file (proves file download works on Vercel)
@app.post("/api/report/generate/{ride_id}")
def generate_report(ride_id: str):
    output_path = f"/tmp/{ride_id}_report.txt"
    with open(output_path, "w") as f:
        f.write(f"Report for ride: {ride_id}\n")
        f.write("This is a demo text report generated by a Vercel serverless function.\n")
        f.write("Replace with your real PDF generator when ready.\n")
    if not os.path.exists(output_path):
        raise HTTPException(status_code=500, detail="Failed to create report")
    return FileResponse(
        output_path,
        media_type="text/plain",
        filename=f"{ride_id}_report.txt"
    )
